# Kakao OAuth Settings

# client-id : REST API KEY
spring.security.oauth2.client.registration.kakao.client-id=cf90c30651b36a2ec22ea27d21520b57
# client-secret : Client Secret ?? => ? ?????? > ?? > client secret
spring.security.oauth2.client.registration.kakao.client-secret=hrF3lTqZn3atX7PvYbrJMrXUIFbj4bfr
# redirect-uri : ???? ???? ??? ? ??? ??? URL
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
# authorization-grant-type : ACCESS TOKEN ?? ?, ??? ???? ?? ??
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
# scope : ??? ?? ?? ??? ???? ??
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
# client-name : ?????? ???? ?? ??, ??? ????? naver, ?? ????? google
spring.security.oauth2.client.registration.kakao.client-name=Kakao
# client-authentication-method : ?? ??? ACCESS ??? ??? ? ?? ?? ??? ????? ??
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post

# authorization-uri : ?? ?? ?? URI (?? ??)
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
# token-uri : ??? ?? ?? URI (?? ??)
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
# user-info-uri : ??? ?? ?? URI (??? ??)
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
# user-name-attribute : ??? ??? ?? ??? ? ??
spring.security.oauth2.client.provider.kakao.user-name-attribute=id





