spring:
  security:
    user:
      name: user
      password: 1234

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
kakao:
  client_id: ${KAKAO_ID}
  client_secret: ${KAKAO_SECRET}
  
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: pjx-server-s3
  
# local 프로파일에서만 적용될 설정
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8443
kakao:
  redirect_uri: http://localhost:5173/auth/kakao

# dev 프로파일에서만 적용될 설정
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 443
kakao:
  redirect_uri: https://pjx-client.vercel.app/auth/kakao


