spring:
  security:
    user:
      name: user
      password: 1234

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
kakao:
  client_id: ${KAKAO_ID}
  client_secret: ${KAKAO_SECRET}
  redirect_uri: ${KAKAO_REDIRECT_DEV}
  
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: pjx-server-s3



